"""
This type stub file was generated by pyright.
"""

import jsonrpclib.history as history
import jsonrpclib.utils as utils
from jsonrpclib.jsonrpc import AppError, Fault, MultiCall, ProtocolError, Server, ServerProxy, TransportError, dump, dumps, jdumps, jloads, load, loads

"""
Aliases to ease access to jsonrpclib classes

:authors: Josh Marshall, Thomas Calmant
:copyright: Copyright 2025, Thomas Calmant
:license: Apache License 2.0
:version: 0.4.3.4

..

    Copyright 2025 Thomas Calmant

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
__version_info__ = ...
__version__ = ...
__docformat__ = ...
