"""
This type stub file was generated by pyright.
"""

"""
The history module.

:authors: Josh Marshall, Thomas Calmant
:copyright: Copyright 2025, Thomas Calmant
:license: Apache License 2.0
:version: 0.4.3.4

..

    Copyright 2025 Thomas Calmant

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
__version_info__ = ...
__version__ = ...
__docformat__ = ...
class History:
    """
    This holds all the response and request objects for a
    session. A server using this should call "clear" after
    each request cycle in order to keep it from clogging
    memory.
    """
    def __init__(self) -> None:
        """
        Sets up members
        """
        ...
    
    def add_response(self, response_obj): # -> None:
        """
        Adds a response to the history

        :param response_obj: Response content
        """
        ...
    
    def add_request(self, request_obj): # -> None:
        """
        Adds a request to the history

        :param request_obj: A request object
        """
        ...
    
    @property
    def request(self): # -> None:
        """
        Returns the latest stored request or None
        """
        ...
    
    @property
    def response(self): # -> None:
        """
        Returns the latest stored response or None
        """
        ...
    
    def clear(self): # -> None:
        """
        Clears the history lists
        """
        ...
    


